### ISSUE TITLE
IIGO nil pointer dereference

### ISSUE THREAD

**Issue by mpardalos** [SOMAS2020/SOMAS2020#167]
I got the clients to contribute something to the common pool to get IIGO to run and this was the result:

<details>
<summary>Output</summary>
<p>

`> go run .  -foragingMaxDeerPerHunt 60 -maxTurns 500 -initialResources 500`

```
2020/12/28 19:53:06 [SERVER]: start runTurn
2020/12/28 19:53:06 [SERVER]: TURN: 1, Season: 1
2020/12/28 19:53:06 [SERVER]: start runOrgs
2020/12/28 19:53:06 [SERVER]: start runIIGO
2020/12/28 19:53:06 [SERVER]: Could not run IIGO since President has no resources to spend
2020/12/28 19:53:06 [SERVER]: finish runIIGO
2020/12/28 19:53:06 [SERVER]: start runIIFO
2020/12/28 19:53:06 [SERVER]: start runPredictionSession
2020/12/28 19:53:06 [Team1]: Final Prediction: [{1.2 1.2 1.2 1 100}]
2020/12/28 19:53:06 [Team2]: Final Prediction: [{1.2 1.2 1.2 1 100}]
2020/12/28 19:53:06 [Team3]: Final Prediction: [{1.2 1.2 1.2 1 100}]
2020/12/28 19:53:06 [Team4]: Final Prediction: [{1.2 1.2 1.2 1 100}]
2020/12/28 19:53:06 [Team5]: Final Prediction: [{1.2 1.2 1.2 1 100}]
2020/12/28 19:53:06 [Team6]: Final Prediction: [{1.2 1.2 1.2 1 100}]
2020/12/28 19:53:06 [SERVER]: finish runPredictionSession
2020/12/28 19:53:06 [SERVER]: Run Forage Predictions
2020/12/28 19:53:06 [SERVER]: Getting Forage Information
2020/12/28 19:53:06 [SERVER]: Distributing Forage Information
2020/12/28 19:53:06 [SERVER]: Finish Running Forage Predictions
2020/12/28 19:53:06 [SERVER]: finish runIIFO
2020/12/28 19:53:06 [SERVER]: start runIITO
2020/12/28 19:53:06 [SERVER]: start runGiftSession
2020/12/28 19:53:06 [SERVER]: Gifts from Team4: map[Team1:{Team1 Team4 0 0 0} Team2:{Team2 Team4 0 0 0} Team3:{Team3 Team4 0 0 0} Team5:{Team5 Team4 0 0 0} Team6:{Team6 Team4 0 0 0}]
2020/12/28 19:53:06 [SERVER]: Gifts from Team5: map[Team1:{Team1 Team5 0 0 0} Team2:{Team2 Team5 0 0 0} Team3:{Team3 Team5 0 0 0} Team4:{Team4 Team5 0 0 0} Team6:{Team6 Team5 0 0 0}]
2020/12/28 19:53:06 [SERVER]: Gifts from Team6: map[Team1:{Team1 Team6 0 0 0} Team2:{Team2 Team6 0 0 0} Team3:{Team3 Team6 0 0 0} Team4:{Team4 Team6 0 0 0} Team5:{Team5 Team6 0 0 0}]
2020/12/28 19:53:06 [SERVER]: Gifts from Team1: map[Team2:{Team2 Team1 0 0 0} Team3:{Team3 Team1 0 0 0} Team4:{Team4 Team1 0 0 0} Team5:{Team5 Team1 0 0 0} Team6:{Team6 Team1 0 0 0}]
2020/12/28 19:53:06 [SERVER]: Gifts from Team2: map[Team1:{Team1 Team2 0 0 0} Team3:{Team3 Team2 0 0 0} Team4:{Team4 Team2 0 0 0} Team5:{Team5 Team2 0 0 0} Team6:{Team6 Team2 0 0 0}]
2020/12/28 19:53:06 [SERVER]: Gifts from Team3: map[Team1:{Team1 Team3 0 0 0} Team2:{Team2 Team3 0 0 0} Team4:{Team4 Team3 0 0 0} Team5:{Team5 Team3 0 0 0} Team6:{Team6 Team3 0 0 0}]
2020/12/28 19:53:06 [SERVER]: finish runGiftSession
2020/12/28 19:53:06 [SERVER]: finish runIITO
2020/12/28 19:53:06 [SERVER]: finish runOrgs
2020/12/28 19:53:06 [SERVER]: start endOfTurn
2020/12/28 19:53:06 [SERVER]: start runOrgsEndOfTurn
2020/12/28 19:53:06 [SERVER]: start runIIGOEndOfTurn
2020/12/28 19:53:06 [SERVER]: Took 25 from Team1 (reason: tax)
2020/12/28 19:53:06 [SERVER]: Took 25 from Team2 (reason: tax)
2020/12/28 19:53:06 [SERVER]: Took 25 from Team3 (reason: tax)
2020/12/28 19:53:06 [SERVER]: Took 25 from Team4 (reason: tax)
2020/12/28 19:53:06 [SERVER]: Took 25 from Team5 (reason: tax)
2020/12/28 19:53:06 [SERVER]: Took 25 from Team6 (reason: tax)
2020/12/28 19:53:06 [SERVER]: finish runIIGOEndOfTurn
2020/12/28 19:53:06 [SERVER]: start runIIFOEndOfTurn
2020/12/28 19:53:06 [SERVER]: finish runIIFOEndOfTurn
2020/12/28 19:53:06 [SERVER]: start runIITOEndOfTurn
2020/12/28 19:53:06 [SERVER]: finish runIITOEndOfTurn
2020/12/28 19:53:06 [SERVER]: finish runOrgsEndOfTurn
2020/12/28 19:53:06 [SERVER]: start runForage
2020/12/28 19:53:06 [Team2]: [Forage][Decision]:Random
2020/12/28 19:53:06 [Team3]: [Forage][Decision]:Random
2020/12/28 19:53:06 [Team4]: [Forage][Decision]:Random
2020/12/28 19:53:06 [Team5]: [Forage][Decision]:Random
2020/12/28 19:53:06 [Team6]: [Forage][Decision]:Random
2020/12/28 19:53:06 [Team1]: [Forage][Decision]:Random
2020/12/28 19:53:06 [SERVER]: Took 28.72136367903193 from Team2 (reason: deer hunt participation)
2020/12/28 19:53:06 [SERVER]: Took 44.67418168213809 from Team3 (reason: deer hunt participation)
2020/12/28 19:53:06 [SERVER]: Took 31.566602527878295 from Team4 (reason: deer hunt participation)
2020/12/28 19:53:06 [SERVER]: Took 20.791423891381562 from Team5 (reason: deer hunt participation)
2020/12/28 19:53:06 [SERVER]: Took 20.170281110885124 from Team6 (reason: deer hunt participation)
2020/12/28 19:53:06 [SERVER]: Took 32.6240959611877 from Team1 (reason: deer hunt participation)
2020/12/28 19:53:06 [SERVER]: start runDeerHunt
2020/12/28 19:53:06 [SERVER]: Gave 17.53556163663342 to Team2 (reason: Deer hunt return)
2020/12/28 19:53:06 [Team2]: [Forage][Update]: ForageType DeerForageType | Profit -11.18580204239851 | Contribution 28.72136367903193 | Actual ROI -0.3894592947397104
2020/12/28 19:53:06 [SERVER]: Gave 27.275406391138898 to Team3 (reason: Deer hunt return)
2020/12/28 19:53:06 [Team3]: [Forage][Update]: ForageType DeerForageType | Profit -17.398775290999193 | Contribution 44.67418168213809 | Actual ROI -0.3894592947397105
2020/12/28 19:53:06 [SERVER]: Gave 19.272695770042056 to Team4 (reason: Deer hunt return)
2020/12/28 19:53:06 [Team4]: [Forage][Update]: ForageType DeerForageType | Profit -12.29390675783624 | Contribution 31.566602527878295 | Actual ROI -0.3894592947397104
2020/12/28 19:53:06 [SERVER]: Gave 12.694010606009734 to Team5 (reason: Deer hunt return)
2020/12/28 19:53:06 [Team5]: [Forage][Update]: ForageType DeerForageType | Profit -8.097413285371829 | Contribution 20.791423891381562 | Actual ROI -0.3894592947397104
2020/12/28 19:53:06 [SERVER]: Gave 12.314777654738101 to Team6 (reason: Deer hunt return)
2020/12/28 19:53:06 [Team6]: [Forage][Update]: ForageType DeerForageType | Profit -7.855503456147023 | Contribution 20.170281110885124 | Actual ROI -0.3894592947397104
2020/12/28 19:53:06 [SERVER]: Gave 19.918338556622903 to Team1 (reason: Deer hunt return)
2020/12/28 19:53:06 [Team1]: [Forage][Update]: ForageType DeerForageType | Profit -12.705757404564796 | Contribution 32.6240959611877 | Actual ROI -0.3894592947397104
2020/12/28 19:53:06 [SERVER]: Hunt generated a return of 109.011 from input of 178.548
2020/12/28 19:53:06 [SERVER]: finish runDeerHunt
2020/12/28 19:53:06 [SERVER]: finish runForage
2020/12/28 19:53:06 [SERVER]: start probeDisaster
2020/12/28 19:53:06 [SERVER]: No disaster reported.
2020/12/28 19:53:06 [SERVER]: finish probeDisaster
2020/12/28 19:53:06 [SERVER]: start incrementTurnAndSeason
2020/12/28 19:53:06 [SERVER]: finish incrementTurnAndSeason
2020/12/28 19:53:06 [SERVER]: start deductCostOfLiving
2020/12/28 19:53:06 [SERVER]: finish deductCostOfLiving
2020/12/28 19:53:06 [SERVER]: start updateIslandLivingStatus
2020/12/28 19:53:06 [SERVER]: finish updateIslandLivingStatus
2020/12/28 19:53:06 [SERVER]: finish endOfTurn
2020/12/28 19:53:06 [SERVER]: finish runTurn
2020/12/28 19:53:06 [SERVER]: start runTurn
2020/12/28 19:53:06 [SERVER]: TURN: 2, Season: 1
2020/12/28 19:53:06 [SERVER]: start runOrgs
2020/12/28 19:53:06 [SERVER]: start runIIGO
2020/12/28 19:53:06 [SERVER]: finish runIIGO
2020/12/28 19:53:06 [SERVER]: finish runOrgs
2020/12/28 19:53:06 [SERVER]: finish runTurn
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4f7eec]

goroutine 1 [running]:
github.com/SOMAS2020/SOMAS2020/internal/server/iigointernal.(*judiciary).inspectHistory(...)
	/home/mpardalos/Documents/go/src/SOMAS2020/internal/server/iigointernal/judiciary.go:75
github.com/SOMAS2020/SOMAS2020/internal/server/iigointernal.RunIIGO(0xc0000ca160, 0xc0000ca2b8, 0x8, 0x8, 0x0)
	/home/mpardalos/Documents/go/src/SOMAS2020/internal/server/iigointernal/orchestration.go:117 +0x46c
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runIIGO(0xc0000ca160, 0x0, 0x0)
	/home/mpardalos/Documents/go/src/SOMAS2020/internal/server/iigo.go:16 +0x10c
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runOrgs(0xc0000ca160, 0x0, 0x0)
	/home/mpardalos/Documents/go/src/SOMAS2020/internal/server/turn.go:41 +0xd7
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runTurn(0xc0000ca160, 0x0, 0x0)
	/home/mpardalos/Documents/go/src/SOMAS2020/internal/server/turn.go:18 +0x19f
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).EntryPoint(0xc0000ca160, 0x1f4, 0x407f400000000000, 0x4024000000000000, 0x4014000000000000, 0x3)
	/home/mpardalos/Documents/go/src/SOMAS2020/internal/server/server.go:91 +0x16d
main.main()
	/home/mpardalos/Documents/go/src/SOMAS2020/main.go:63 +0xbf
exit status 2
```
</p>
</details>

**Comment by Neelesh99** [comment]
Apologies it seems that in baseclient_iigo.go we haven't passed in the base implementations of the roles. I'll make a quick fix for this via PR, but for more immediate remedy on lines 33, 38 and 43 of baseclient_iigo return references to the base[roles] provided in the baseclient folder.

**Comment by Neelesh99** [comment]
#168 opened to fix

**Comment by Neelesh99** [comment]
Can this be closed? @mpardalos

**Comment by mpardalos** [comment]
Yup it's good now. Closing.
