### ISSUE TITLE
[IIGO/VOTING] OpenBallot breaks simulation after PR #222 

### ISSUE THREAD

**Issue by Eirikalb** [SOMAS2020/SOMAS2020#286]
PR #222 

This error happened after running `go run .` 

````
2021/01/05 17:55:27 [SERVER]: finish runTurn
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/SOMAS2020/SOMAS2020/internal/common/voting.(*Election).OpenBallot(0xc00008ea70, 0xc0001e2980, 0x6, 0x8, 0xc00007c8a0)
        C:/Users/eirik/Documents/GitHub/SOMAS2020/internal/common/voting/election.go:72 +0xb07
github.com/SOMAS2020/SOMAS2020/internal/server/iigointernal.(*executive).appointNextSpeaker(0xc6b160, 0xb70101, 0x0, 0xc0001e2980, 0x6, 0x8, 0x5, 0x0, 0x0)
        C:/Users/eirik/Documents/GitHub/SOMAS2020/internal/server/iigointernal/executive.go:158 +0x19d
github.com/SOMAS2020/SOMAS2020/internal/server/iigointernal.RunIIGO(0xc0000982c0, 0xc000098548, 0xc000098398, 0x8, 0x0, 0x0)
        C:/Users/eirik/Documents/GitHub/SOMAS2020/internal/server/iigointernal/orchestration.go:207 +0xd78     
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runIIGO(0xc0000982c0, 0x0, 0x0)
        C:/Users/eirik/Documents/GitHub/SOMAS2020/internal/server/iigo.go:16 +0x125
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runOrgs(0xc0000982c0, 0x0, 0x0)
        C:/Users/eirik/Documents/GitHub/SOMAS2020/internal/server/turn.go:43 +0xde
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runTurn(0xc0000982c0, 0x0, 0x0)
        C:/Users/eirik/Documents/GitHub/SOMAS2020/internal/server/turn.go:18 +0x1a9
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).EntryPoint(0xc0000982c0, 0xa, 0x4059000000000000, 0x4059000000000000, 0x4024000000000000, 0x4014000000000000)
        C:/Users/eirik/Documents/GitHub/SOMAS2020/internal/server/server.go:100 +0x1c5
main.main()
        C:/Users/eirik/Documents/GitHub/SOMAS2020/main.go:65 +0x1df
exit status 2
````

**Comment by Ning-72** [comment]
I have deleted changes on openballots in my new PR, hope that would be helpful. #283

**Comment by preetl** [comment]
Behaviour is now as expected - OpenBallot func tests added in #290 which pass.
